<script src="<?php echo base_url('assets/') ?>plugins/jquery/jquery.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/jquery-ui/jquery-ui.min.js"></script>
<script>
    $.widget.bridge("uibutton", $.ui.button);
</script>
<script src="<?php echo base_url('assets/') ?>plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/chart.js/Chart.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/sparklines/sparkline.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/jquery-knob/jquery.knob.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/moment/moment.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/summernote/summernote-bs4.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/jquery-mousewheel/jquery.mousewheel.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/raphael/raphael.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/jquery-mapael/jquery.mapael.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/jquery-mapael/maps/usa_states.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/flot/jquery.flot.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/flot/plugins/jquery.flot.resize.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/flot/plugins/jquery.flot.pie.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/uplot/uPlot.iife.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/ion-rangeslider/js/ion.rangeSlider.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/bootstrap-slider/bootstrap-slider.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/toastr/toastr.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/summernote/summernote-bs4.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/codemirror/codemirror.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/codemirror/mode/css/css.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/codemirror/mode/xml/xml.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/codemirror/mode/htmlmixed/htmlmixed.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/jquery-validation/jquery.validate.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/jquery-validation/additional-methods.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/jszip/jszip.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/pdfmake/pdfmake.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/pdfmake/vfs_fonts.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/daterangepicker/daterangepicker.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/jsgrid/demos/db.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/jsgrid/jsgrid.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/moment/moment.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/fullcalendar/main.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/ekko-lightbox/ekko-lightbox.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/filterizr/jquery.filterizr.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/select2/js/select2.full.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/inputmask/jquery.inputmask.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/bootstrap-switch/js/bootstrap-switch.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/bs-stepper/js/bs-stepper.min.js"></script>
<script src="<?php echo base_url('assets/') ?>plugins/dropzone/min/dropzone.min.js"></script>
<script src="<?php echo base_url('assets/') ?>dist/js/adminlte.js"></script>
<script src="<?php echo base_url('assets/') ?>dist/js/demo.js"></script>
<script src="<?php echo base_url('assets/') ?>dist/js/pages/dashboard.js"></script>
<script src="<?php echo base_url('assets/') ?>dist/js/pages/dashboard2.js"></script>
<script src="<?php echo base_url('assets/') ?>dist/js/pages/dashboard3.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
<script>
    const baseUrl = "<?php echo base_url(); ?>";
</script>